// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armor_detection.proto

#ifndef PROTOBUF_INCLUDED_armor_5fdetection_2eproto
#define PROTOBUF_INCLUDED_armor_5fdetection_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_armor_5fdetection_2eproto 

namespace protobuf_armor_5fdetection_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_armor_5fdetection_2eproto
namespace armor_detection {
class ArmorDetectionParam;
class ArmorDetectionParamDefaultTypeInternal;
extern ArmorDetectionParamDefaultTypeInternal _ArmorDetectionParam_default_instance_;
}  // namespace armor_detection
namespace google {
namespace protobuf {
template<> ::armor_detection::ArmorDetectionParam* Arena::CreateMaybeMessage<::armor_detection::ArmorDetectionParam>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace armor_detection {

// ===================================================================

class ArmorDetectionParam : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:armor_detection.ArmorDetectionParam) */ {
 public:
  ArmorDetectionParam();
  virtual ~ArmorDetectionParam();

  ArmorDetectionParam(const ArmorDetectionParam& from);

  inline ArmorDetectionParam& operator=(const ArmorDetectionParam& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArmorDetectionParam(ArmorDetectionParam&& from) noexcept
    : ArmorDetectionParam() {
    *this = ::std::move(from);
  }

  inline ArmorDetectionParam& operator=(ArmorDetectionParam&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArmorDetectionParam& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArmorDetectionParam* internal_default_instance() {
    return reinterpret_cast<const ArmorDetectionParam*>(
               &_ArmorDetectionParam_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ArmorDetectionParam* other);
  friend void swap(ArmorDetectionParam& a, ArmorDetectionParam& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArmorDetectionParam* New() const final {
    return CreateMaybeMessage<ArmorDetectionParam>(NULL);
  }

  ArmorDetectionParam* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArmorDetectionParam>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ArmorDetectionParam& from);
  void MergeFrom(const ArmorDetectionParam& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArmorDetectionParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 undetected_armor_delay = 1;
  bool has_undetected_armor_delay() const;
  void clear_undetected_armor_delay();
  static const int kUndetectedArmorDelayFieldNumber = 1;
  ::google::protobuf::uint32 undetected_armor_delay() const;
  void set_undetected_armor_delay(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:armor_detection.ArmorDetectionParam)
 private:
  void set_has_undetected_armor_delay();
  void clear_has_undetected_armor_delay();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 undetected_armor_delay_;
  friend struct ::protobuf_armor_5fdetection_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ArmorDetectionParam

// optional uint32 undetected_armor_delay = 1;
inline bool ArmorDetectionParam::has_undetected_armor_delay() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ArmorDetectionParam::set_has_undetected_armor_delay() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ArmorDetectionParam::clear_has_undetected_armor_delay() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ArmorDetectionParam::clear_undetected_armor_delay() {
  undetected_armor_delay_ = 0u;
  clear_has_undetected_armor_delay();
}
inline ::google::protobuf::uint32 ArmorDetectionParam::undetected_armor_delay() const {
  // @@protoc_insertion_point(field_get:armor_detection.ArmorDetectionParam.undetected_armor_delay)
  return undetected_armor_delay_;
}
inline void ArmorDetectionParam::set_undetected_armor_delay(::google::protobuf::uint32 value) {
  set_has_undetected_armor_delay();
  undetected_armor_delay_ = value;
  // @@protoc_insertion_point(field_set:armor_detection.ArmorDetectionParam.undetected_armor_delay)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace armor_detection

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_armor_5fdetection_2eproto
