// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: decision.proto

#ifndef PROTOBUF_INCLUDED_decision_2eproto
#define PROTOBUF_INCLUDED_decision_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_decision_2eproto 

namespace protobuf_decision_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_decision_2eproto
namespace roborts_decision {
class BlueOrRedGroup;
class BlueOrRedGroupDefaultTypeInternal;
extern BlueOrRedGroupDefaultTypeInternal _BlueOrRedGroup_default_instance_;
class DecisionConfig;
class DecisionConfigDefaultTypeInternal;
extern DecisionConfigDefaultTypeInternal _DecisionConfig_default_instance_;
class EscapeConstraint;
class EscapeConstraintDefaultTypeInternal;
extern EscapeConstraintDefaultTypeInternal _EscapeConstraint_default_instance_;
class MultiRobot;
class MultiRobotDefaultTypeInternal;
extern MultiRobotDefaultTypeInternal _MultiRobot_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class SearchConstraint;
class SearchConstraintDefaultTypeInternal;
extern SearchConstraintDefaultTypeInternal _SearchConstraint_default_instance_;
class WhirlVel;
class WhirlVelDefaultTypeInternal;
extern WhirlVelDefaultTypeInternal _WhirlVel_default_instance_;
}  // namespace roborts_decision
namespace google {
namespace protobuf {
template<> ::roborts_decision::BlueOrRedGroup* Arena::CreateMaybeMessage<::roborts_decision::BlueOrRedGroup>(Arena*);
template<> ::roborts_decision::DecisionConfig* Arena::CreateMaybeMessage<::roborts_decision::DecisionConfig>(Arena*);
template<> ::roborts_decision::EscapeConstraint* Arena::CreateMaybeMessage<::roborts_decision::EscapeConstraint>(Arena*);
template<> ::roborts_decision::MultiRobot* Arena::CreateMaybeMessage<::roborts_decision::MultiRobot>(Arena*);
template<> ::roborts_decision::Point* Arena::CreateMaybeMessage<::roborts_decision::Point>(Arena*);
template<> ::roborts_decision::SearchConstraint* Arena::CreateMaybeMessage<::roborts_decision::SearchConstraint>(Arena*);
template<> ::roborts_decision::WhirlVel* Arena::CreateMaybeMessage<::roborts_decision::WhirlVel>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace roborts_decision {

// ===================================================================

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(Point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Point* other);
  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(NULL);
  }

  Point* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // float roll = 4;
  void clear_roll();
  static const int kRollFieldNumber = 4;
  float roll() const;
  void set_roll(float value);

  // float pitch = 5;
  void clear_pitch();
  static const int kPitchFieldNumber = 5;
  float pitch() const;
  void set_pitch(float value);

  // float yaw = 6;
  void clear_yaw();
  static const int kYawFieldNumber = 6;
  float yaw() const;
  void set_yaw(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.Point)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  float roll_;
  float pitch_;
  float yaw_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EscapeConstraint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.EscapeConstraint) */ {
 public:
  EscapeConstraint();
  virtual ~EscapeConstraint();

  EscapeConstraint(const EscapeConstraint& from);

  inline EscapeConstraint& operator=(const EscapeConstraint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EscapeConstraint(EscapeConstraint&& from) noexcept
    : EscapeConstraint() {
    *this = ::std::move(from);
  }

  inline EscapeConstraint& operator=(EscapeConstraint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const EscapeConstraint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EscapeConstraint* internal_default_instance() {
    return reinterpret_cast<const EscapeConstraint*>(
               &_EscapeConstraint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(EscapeConstraint* other);
  friend void swap(EscapeConstraint& a, EscapeConstraint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EscapeConstraint* New() const final {
    return CreateMaybeMessage<EscapeConstraint>(NULL);
  }

  EscapeConstraint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EscapeConstraint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const EscapeConstraint& from);
  void MergeFrom(const EscapeConstraint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EscapeConstraint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float left_x_limit = 1;
  void clear_left_x_limit();
  static const int kLeftXLimitFieldNumber = 1;
  float left_x_limit() const;
  void set_left_x_limit(float value);

  // float right_x_limit = 2;
  void clear_right_x_limit();
  static const int kRightXLimitFieldNumber = 2;
  float right_x_limit() const;
  void set_right_x_limit(float value);

  // float robot_x_limit = 3;
  void clear_robot_x_limit();
  static const int kRobotXLimitFieldNumber = 3;
  float robot_x_limit() const;
  void set_robot_x_limit(float value);

  // float left_random_min_x = 4;
  void clear_left_random_min_x();
  static const int kLeftRandomMinXFieldNumber = 4;
  float left_random_min_x() const;
  void set_left_random_min_x(float value);

  // float left_random_max_x = 5;
  void clear_left_random_max_x();
  static const int kLeftRandomMaxXFieldNumber = 5;
  float left_random_max_x() const;
  void set_left_random_max_x(float value);

  // float right_random_min_x = 6;
  void clear_right_random_min_x();
  static const int kRightRandomMinXFieldNumber = 6;
  float right_random_min_x() const;
  void set_right_random_min_x(float value);

  // float right_random_max_x = 7;
  void clear_right_random_max_x();
  static const int kRightRandomMaxXFieldNumber = 7;
  float right_random_max_x() const;
  void set_right_random_max_x(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.EscapeConstraint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float left_x_limit_;
  float right_x_limit_;
  float robot_x_limit_;
  float left_random_min_x_;
  float left_random_max_x_;
  float right_random_min_x_;
  float right_random_max_x_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchConstraint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.SearchConstraint) */ {
 public:
  SearchConstraint();
  virtual ~SearchConstraint();

  SearchConstraint(const SearchConstraint& from);

  inline SearchConstraint& operator=(const SearchConstraint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SearchConstraint(SearchConstraint&& from) noexcept
    : SearchConstraint() {
    *this = ::std::move(from);
  }

  inline SearchConstraint& operator=(SearchConstraint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchConstraint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchConstraint* internal_default_instance() {
    return reinterpret_cast<const SearchConstraint*>(
               &_SearchConstraint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SearchConstraint* other);
  friend void swap(SearchConstraint& a, SearchConstraint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SearchConstraint* New() const final {
    return CreateMaybeMessage<SearchConstraint>(NULL);
  }

  SearchConstraint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SearchConstraint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SearchConstraint& from);
  void MergeFrom(const SearchConstraint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchConstraint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x_limit = 1;
  void clear_x_limit();
  static const int kXLimitFieldNumber = 1;
  float x_limit() const;
  void set_x_limit(float value);

  // float y_limit = 2;
  void clear_y_limit();
  static const int kYLimitFieldNumber = 2;
  float y_limit() const;
  void set_y_limit(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.SearchConstraint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_limit_;
  float y_limit_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class WhirlVel : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.WhirlVel) */ {
 public:
  WhirlVel();
  virtual ~WhirlVel();

  WhirlVel(const WhirlVel& from);

  inline WhirlVel& operator=(const WhirlVel& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WhirlVel(WhirlVel&& from) noexcept
    : WhirlVel() {
    *this = ::std::move(from);
  }

  inline WhirlVel& operator=(WhirlVel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const WhirlVel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WhirlVel* internal_default_instance() {
    return reinterpret_cast<const WhirlVel*>(
               &_WhirlVel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(WhirlVel* other);
  friend void swap(WhirlVel& a, WhirlVel& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WhirlVel* New() const final {
    return CreateMaybeMessage<WhirlVel>(NULL);
  }

  WhirlVel* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WhirlVel>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WhirlVel& from);
  void MergeFrom(const WhirlVel& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WhirlVel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float angle_x_vel = 1;
  void clear_angle_x_vel();
  static const int kAngleXVelFieldNumber = 1;
  float angle_x_vel() const;
  void set_angle_x_vel(float value);

  // float angle_y_vel = 2;
  void clear_angle_y_vel();
  static const int kAngleYVelFieldNumber = 2;
  float angle_y_vel() const;
  void set_angle_y_vel(float value);

  // float angle_z_vel = 3;
  void clear_angle_z_vel();
  static const int kAngleZVelFieldNumber = 3;
  float angle_z_vel() const;
  void set_angle_z_vel(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.WhirlVel)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float angle_x_vel_;
  float angle_y_vel_;
  float angle_z_vel_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MultiRobot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.MultiRobot) */ {
 public:
  MultiRobot();
  virtual ~MultiRobot();

  MultiRobot(const MultiRobot& from);

  inline MultiRobot& operator=(const MultiRobot& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MultiRobot(MultiRobot&& from) noexcept
    : MultiRobot() {
    *this = ::std::move(from);
  }

  inline MultiRobot& operator=(MultiRobot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MultiRobot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MultiRobot* internal_default_instance() {
    return reinterpret_cast<const MultiRobot*>(
               &_MultiRobot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(MultiRobot* other);
  friend void swap(MultiRobot& a, MultiRobot& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MultiRobot* New() const final {
    return CreateMaybeMessage<MultiRobot>(NULL);
  }

  MultiRobot* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MultiRobot>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MultiRobot& from);
  void MergeFrom(const MultiRobot& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MultiRobot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .roborts_decision.Point start_position = 7;
  bool has_start_position() const;
  void clear_start_position();
  static const int kStartPositionFieldNumber = 7;
  private:
  const ::roborts_decision::Point& _internal_start_position() const;
  public:
  const ::roborts_decision::Point& start_position() const;
  ::roborts_decision::Point* release_start_position();
  ::roborts_decision::Point* mutable_start_position();
  void set_allocated_start_position(::roborts_decision::Point* start_position);

  // @@protoc_insertion_point(class_scope:roborts_decision.MultiRobot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::roborts_decision::Point* start_position_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BlueOrRedGroup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.BlueOrRedGroup) */ {
 public:
  BlueOrRedGroup();
  virtual ~BlueOrRedGroup();

  BlueOrRedGroup(const BlueOrRedGroup& from);

  inline BlueOrRedGroup& operator=(const BlueOrRedGroup& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BlueOrRedGroup(BlueOrRedGroup&& from) noexcept
    : BlueOrRedGroup() {
    *this = ::std::move(from);
  }

  inline BlueOrRedGroup& operator=(BlueOrRedGroup&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BlueOrRedGroup& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BlueOrRedGroup* internal_default_instance() {
    return reinterpret_cast<const BlueOrRedGroup*>(
               &_BlueOrRedGroup_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(BlueOrRedGroup* other);
  friend void swap(BlueOrRedGroup& a, BlueOrRedGroup& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BlueOrRedGroup* New() const final {
    return CreateMaybeMessage<BlueOrRedGroup>(NULL);
  }

  BlueOrRedGroup* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BlueOrRedGroup>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BlueOrRedGroup& from);
  void MergeFrom(const BlueOrRedGroup& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlueOrRedGroup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .roborts_decision.Point patrol = 5;
  int patrol_size() const;
  void clear_patrol();
  static const int kPatrolFieldNumber = 5;
  ::roborts_decision::Point* mutable_patrol(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_patrol();
  const ::roborts_decision::Point& patrol(int index) const;
  ::roborts_decision::Point* add_patrol();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      patrol() const;

  // .roborts_decision.MultiRobot master_bot = 1;
  bool has_master_bot() const;
  void clear_master_bot();
  static const int kMasterBotFieldNumber = 1;
  private:
  const ::roborts_decision::MultiRobot& _internal_master_bot() const;
  public:
  const ::roborts_decision::MultiRobot& master_bot() const;
  ::roborts_decision::MultiRobot* release_master_bot();
  ::roborts_decision::MultiRobot* mutable_master_bot();
  void set_allocated_master_bot(::roborts_decision::MultiRobot* master_bot);

  // .roborts_decision.MultiRobot wing_bot = 2;
  bool has_wing_bot() const;
  void clear_wing_bot();
  static const int kWingBotFieldNumber = 2;
  private:
  const ::roborts_decision::MultiRobot& _internal_wing_bot() const;
  public:
  const ::roborts_decision::MultiRobot& wing_bot() const;
  ::roborts_decision::MultiRobot* release_wing_bot();
  ::roborts_decision::MultiRobot* mutable_wing_bot();
  void set_allocated_wing_bot(::roborts_decision::MultiRobot* wing_bot);

  // .roborts_decision.Point reload_point = 3;
  bool has_reload_point() const;
  void clear_reload_point();
  static const int kReloadPointFieldNumber = 3;
  private:
  const ::roborts_decision::Point& _internal_reload_point() const;
  public:
  const ::roborts_decision::Point& reload_point() const;
  ::roborts_decision::Point* release_reload_point();
  ::roborts_decision::Point* mutable_reload_point();
  void set_allocated_reload_point(::roborts_decision::Point* reload_point);

  // .roborts_decision.Point shield_point = 4;
  bool has_shield_point() const;
  void clear_shield_point();
  static const int kShieldPointFieldNumber = 4;
  private:
  const ::roborts_decision::Point& _internal_shield_point() const;
  public:
  const ::roborts_decision::Point& shield_point() const;
  ::roborts_decision::Point* release_shield_point();
  ::roborts_decision::Point* mutable_shield_point();
  void set_allocated_shield_point(::roborts_decision::Point* shield_point);

  // @@protoc_insertion_point(class_scope:roborts_decision.BlueOrRedGroup)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > patrol_;
  ::roborts_decision::MultiRobot* master_bot_;
  ::roborts_decision::MultiRobot* wing_bot_;
  ::roborts_decision::Point* reload_point_;
  ::roborts_decision::Point* shield_point_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DecisionConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.DecisionConfig) */ {
 public:
  DecisionConfig();
  virtual ~DecisionConfig();

  DecisionConfig(const DecisionConfig& from);

  inline DecisionConfig& operator=(const DecisionConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DecisionConfig(DecisionConfig&& from) noexcept
    : DecisionConfig() {
    *this = ::std::move(from);
  }

  inline DecisionConfig& operator=(DecisionConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DecisionConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DecisionConfig* internal_default_instance() {
    return reinterpret_cast<const DecisionConfig*>(
               &_DecisionConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(DecisionConfig* other);
  friend void swap(DecisionConfig& a, DecisionConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DecisionConfig* New() const final {
    return CreateMaybeMessage<DecisionConfig>(NULL);
  }

  DecisionConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DecisionConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DecisionConfig& from);
  void MergeFrom(const DecisionConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DecisionConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .roborts_decision.Point search_region_1 = 14;
  int search_region_1_size() const;
  void clear_search_region_1();
  static const int kSearchRegion1FieldNumber = 14;
  ::roborts_decision::Point* mutable_search_region_1(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_1();
  const ::roborts_decision::Point& search_region_1(int index) const;
  ::roborts_decision::Point* add_search_region_1();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_1() const;

  // repeated .roborts_decision.Point search_region_2 = 15;
  int search_region_2_size() const;
  void clear_search_region_2();
  static const int kSearchRegion2FieldNumber = 15;
  ::roborts_decision::Point* mutable_search_region_2(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_2();
  const ::roborts_decision::Point& search_region_2(int index) const;
  ::roborts_decision::Point* add_search_region_2();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_2() const;

  // repeated .roborts_decision.Point search_region_3 = 16;
  int search_region_3_size() const;
  void clear_search_region_3();
  static const int kSearchRegion3FieldNumber = 16;
  ::roborts_decision::Point* mutable_search_region_3(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_3();
  const ::roborts_decision::Point& search_region_3(int index) const;
  ::roborts_decision::Point* add_search_region_3();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_3() const;

  // repeated .roborts_decision.Point search_region_4 = 17;
  int search_region_4_size() const;
  void clear_search_region_4();
  static const int kSearchRegion4FieldNumber = 17;
  ::roborts_decision::Point* mutable_search_region_4(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_4();
  const ::roborts_decision::Point& search_region_4(int index) const;
  ::roborts_decision::Point* add_search_region_4();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_4() const;

  // string strategy = 1;
  void clear_strategy();
  static const int kStrategyFieldNumber = 1;
  const ::std::string& strategy() const;
  void set_strategy(const ::std::string& value);
  #if LANG_CXX11
  void set_strategy(::std::string&& value);
  #endif
  void set_strategy(const char* value);
  void set_strategy(const char* value, size_t size);
  ::std::string* mutable_strategy();
  ::std::string* release_strategy();
  void set_allocated_strategy(::std::string* strategy);

  // string master_ip = 6;
  void clear_master_ip();
  static const int kMasterIpFieldNumber = 6;
  const ::std::string& master_ip() const;
  void set_master_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_master_ip(::std::string&& value);
  #endif
  void set_master_ip(const char* value);
  void set_master_ip(const char* value, size_t size);
  ::std::string* mutable_master_ip();
  ::std::string* release_master_ip();
  void set_allocated_master_ip(::std::string* master_ip);

  // string guard_ip = 7;
  void clear_guard_ip();
  static const int kGuardIpFieldNumber = 7;
  const ::std::string& guard_ip() const;
  void set_guard_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_guard_ip(::std::string&& value);
  #endif
  void set_guard_ip(const char* value);
  void set_guard_ip(const char* value, size_t size);
  ::std::string* mutable_guard_ip();
  ::std::string* release_guard_ip();
  void set_allocated_guard_ip(::std::string* guard_ip);

  // .roborts_decision.EscapeConstraint escape = 9;
  bool has_escape() const;
  void clear_escape();
  static const int kEscapeFieldNumber = 9;
  private:
  const ::roborts_decision::EscapeConstraint& _internal_escape() const;
  public:
  const ::roborts_decision::EscapeConstraint& escape() const;
  ::roborts_decision::EscapeConstraint* release_escape();
  ::roborts_decision::EscapeConstraint* mutable_escape();
  void set_allocated_escape(::roborts_decision::EscapeConstraint* escape);

  // .roborts_decision.BlueOrRedGroup blue = 10;
  bool has_blue() const;
  void clear_blue();
  static const int kBlueFieldNumber = 10;
  private:
  const ::roborts_decision::BlueOrRedGroup& _internal_blue() const;
  public:
  const ::roborts_decision::BlueOrRedGroup& blue() const;
  ::roborts_decision::BlueOrRedGroup* release_blue();
  ::roborts_decision::BlueOrRedGroup* mutable_blue();
  void set_allocated_blue(::roborts_decision::BlueOrRedGroup* blue);

  // .roborts_decision.BlueOrRedGroup red = 11;
  bool has_red() const;
  void clear_red();
  static const int kRedFieldNumber = 11;
  private:
  const ::roborts_decision::BlueOrRedGroup& _internal_red() const;
  public:
  const ::roborts_decision::BlueOrRedGroup& red() const;
  ::roborts_decision::BlueOrRedGroup* release_red();
  ::roborts_decision::BlueOrRedGroup* mutable_red();
  void set_allocated_red(::roborts_decision::BlueOrRedGroup* red);

  // .roborts_decision.SearchConstraint search_limit = 12;
  bool has_search_limit() const;
  void clear_search_limit();
  static const int kSearchLimitFieldNumber = 12;
  private:
  const ::roborts_decision::SearchConstraint& _internal_search_limit() const;
  public:
  const ::roborts_decision::SearchConstraint& search_limit() const;
  ::roborts_decision::SearchConstraint* release_search_limit();
  ::roborts_decision::SearchConstraint* mutable_search_limit();
  void set_allocated_search_limit(::roborts_decision::SearchConstraint* search_limit);

  // .roborts_decision.WhirlVel whirl_vel = 13;
  bool has_whirl_vel() const;
  void clear_whirl_vel();
  static const int kWhirlVelFieldNumber = 13;
  private:
  const ::roborts_decision::WhirlVel& _internal_whirl_vel() const;
  public:
  const ::roborts_decision::WhirlVel& whirl_vel() const;
  ::roborts_decision::WhirlVel* release_whirl_vel();
  ::roborts_decision::WhirlVel* mutable_whirl_vel();
  void set_allocated_whirl_vel(::roborts_decision::WhirlVel* whirl_vel);

  // bool use_camera = 2;
  void clear_use_camera();
  static const int kUseCameraFieldNumber = 2;
  bool use_camera() const;
  void set_use_camera(bool value);

  // bool master = 3;
  void clear_master();
  static const int kMasterFieldNumber = 3;
  bool master() const;
  void set_master(bool value);

  // bool isblue = 4;
  void clear_isblue();
  static const int kIsblueFieldNumber = 4;
  bool isblue() const;
  void set_isblue(bool value);

  // bool usewifi = 5;
  void clear_usewifi();
  static const int kUsewifiFieldNumber = 5;
  bool usewifi() const;
  void set_usewifi(bool value);

  // int32 remain_bullet = 8;
  void clear_remain_bullet();
  static const int kRemainBulletFieldNumber = 8;
  ::google::protobuf::int32 remain_bullet() const;
  void set_remain_bullet(::google::protobuf::int32 value);

  // int32 shoot_hz = 19;
  void clear_shoot_hz();
  static const int kShootHzFieldNumber = 19;
  ::google::protobuf::int32 shoot_hz() const;
  void set_shoot_hz(::google::protobuf::int32 value);

  // bool can_shoot = 18;
  void clear_can_shoot();
  static const int kCanShootFieldNumber = 18;
  bool can_shoot() const;
  void set_can_shoot(bool value);

  // bool use_refree = 20;
  void clear_use_refree();
  static const int kUseRefreeFieldNumber = 20;
  bool use_refree() const;
  void set_use_refree(bool value);

  // @@protoc_insertion_point(class_scope:roborts_decision.DecisionConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_1_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_2_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_3_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_4_;
  ::google::protobuf::internal::ArenaStringPtr strategy_;
  ::google::protobuf::internal::ArenaStringPtr master_ip_;
  ::google::protobuf::internal::ArenaStringPtr guard_ip_;
  ::roborts_decision::EscapeConstraint* escape_;
  ::roborts_decision::BlueOrRedGroup* blue_;
  ::roborts_decision::BlueOrRedGroup* red_;
  ::roborts_decision::SearchConstraint* search_limit_;
  ::roborts_decision::WhirlVel* whirl_vel_;
  bool use_camera_;
  bool master_;
  bool isblue_;
  bool usewifi_;
  ::google::protobuf::int32 remain_bullet_;
  ::google::protobuf::int32 shoot_hz_;
  bool can_shoot_;
  bool use_refree_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// float x = 1;
inline void Point::clear_x() {
  x_ = 0;
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.x)
  return x_;
}
inline void Point::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.x)
}

// float y = 2;
inline void Point::clear_y() {
  y_ = 0;
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.y)
  return y_;
}
inline void Point::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.y)
}

// float z = 3;
inline void Point::clear_z() {
  z_ = 0;
}
inline float Point::z() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.z)
  return z_;
}
inline void Point::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.z)
}

// float roll = 4;
inline void Point::clear_roll() {
  roll_ = 0;
}
inline float Point::roll() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.roll)
  return roll_;
}
inline void Point::set_roll(float value) {
  
  roll_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.roll)
}

// float pitch = 5;
inline void Point::clear_pitch() {
  pitch_ = 0;
}
inline float Point::pitch() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.pitch)
  return pitch_;
}
inline void Point::set_pitch(float value) {
  
  pitch_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.pitch)
}

// float yaw = 6;
inline void Point::clear_yaw() {
  yaw_ = 0;
}
inline float Point::yaw() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.yaw)
  return yaw_;
}
inline void Point::set_yaw(float value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.yaw)
}

// -------------------------------------------------------------------

// EscapeConstraint

// float left_x_limit = 1;
inline void EscapeConstraint::clear_left_x_limit() {
  left_x_limit_ = 0;
}
inline float EscapeConstraint::left_x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.left_x_limit)
  return left_x_limit_;
}
inline void EscapeConstraint::set_left_x_limit(float value) {
  
  left_x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.left_x_limit)
}

// float right_x_limit = 2;
inline void EscapeConstraint::clear_right_x_limit() {
  right_x_limit_ = 0;
}
inline float EscapeConstraint::right_x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.right_x_limit)
  return right_x_limit_;
}
inline void EscapeConstraint::set_right_x_limit(float value) {
  
  right_x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.right_x_limit)
}

// float robot_x_limit = 3;
inline void EscapeConstraint::clear_robot_x_limit() {
  robot_x_limit_ = 0;
}
inline float EscapeConstraint::robot_x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.robot_x_limit)
  return robot_x_limit_;
}
inline void EscapeConstraint::set_robot_x_limit(float value) {
  
  robot_x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.robot_x_limit)
}

// float left_random_min_x = 4;
inline void EscapeConstraint::clear_left_random_min_x() {
  left_random_min_x_ = 0;
}
inline float EscapeConstraint::left_random_min_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.left_random_min_x)
  return left_random_min_x_;
}
inline void EscapeConstraint::set_left_random_min_x(float value) {
  
  left_random_min_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.left_random_min_x)
}

// float left_random_max_x = 5;
inline void EscapeConstraint::clear_left_random_max_x() {
  left_random_max_x_ = 0;
}
inline float EscapeConstraint::left_random_max_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.left_random_max_x)
  return left_random_max_x_;
}
inline void EscapeConstraint::set_left_random_max_x(float value) {
  
  left_random_max_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.left_random_max_x)
}

// float right_random_min_x = 6;
inline void EscapeConstraint::clear_right_random_min_x() {
  right_random_min_x_ = 0;
}
inline float EscapeConstraint::right_random_min_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.right_random_min_x)
  return right_random_min_x_;
}
inline void EscapeConstraint::set_right_random_min_x(float value) {
  
  right_random_min_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.right_random_min_x)
}

// float right_random_max_x = 7;
inline void EscapeConstraint::clear_right_random_max_x() {
  right_random_max_x_ = 0;
}
inline float EscapeConstraint::right_random_max_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.right_random_max_x)
  return right_random_max_x_;
}
inline void EscapeConstraint::set_right_random_max_x(float value) {
  
  right_random_max_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.right_random_max_x)
}

// -------------------------------------------------------------------

// SearchConstraint

// float x_limit = 1;
inline void SearchConstraint::clear_x_limit() {
  x_limit_ = 0;
}
inline float SearchConstraint::x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.SearchConstraint.x_limit)
  return x_limit_;
}
inline void SearchConstraint::set_x_limit(float value) {
  
  x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.SearchConstraint.x_limit)
}

// float y_limit = 2;
inline void SearchConstraint::clear_y_limit() {
  y_limit_ = 0;
}
inline float SearchConstraint::y_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.SearchConstraint.y_limit)
  return y_limit_;
}
inline void SearchConstraint::set_y_limit(float value) {
  
  y_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.SearchConstraint.y_limit)
}

// -------------------------------------------------------------------

// WhirlVel

// float angle_x_vel = 1;
inline void WhirlVel::clear_angle_x_vel() {
  angle_x_vel_ = 0;
}
inline float WhirlVel::angle_x_vel() const {
  // @@protoc_insertion_point(field_get:roborts_decision.WhirlVel.angle_x_vel)
  return angle_x_vel_;
}
inline void WhirlVel::set_angle_x_vel(float value) {
  
  angle_x_vel_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.WhirlVel.angle_x_vel)
}

// float angle_y_vel = 2;
inline void WhirlVel::clear_angle_y_vel() {
  angle_y_vel_ = 0;
}
inline float WhirlVel::angle_y_vel() const {
  // @@protoc_insertion_point(field_get:roborts_decision.WhirlVel.angle_y_vel)
  return angle_y_vel_;
}
inline void WhirlVel::set_angle_y_vel(float value) {
  
  angle_y_vel_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.WhirlVel.angle_y_vel)
}

// float angle_z_vel = 3;
inline void WhirlVel::clear_angle_z_vel() {
  angle_z_vel_ = 0;
}
inline float WhirlVel::angle_z_vel() const {
  // @@protoc_insertion_point(field_get:roborts_decision.WhirlVel.angle_z_vel)
  return angle_z_vel_;
}
inline void WhirlVel::set_angle_z_vel(float value) {
  
  angle_z_vel_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.WhirlVel.angle_z_vel)
}

// -------------------------------------------------------------------

// MultiRobot

// .roborts_decision.Point start_position = 7;
inline bool MultiRobot::has_start_position() const {
  return this != internal_default_instance() && start_position_ != NULL;
}
inline void MultiRobot::clear_start_position() {
  if (GetArenaNoVirtual() == NULL && start_position_ != NULL) {
    delete start_position_;
  }
  start_position_ = NULL;
}
inline const ::roborts_decision::Point& MultiRobot::_internal_start_position() const {
  return *start_position_;
}
inline const ::roborts_decision::Point& MultiRobot::start_position() const {
  const ::roborts_decision::Point* p = start_position_;
  // @@protoc_insertion_point(field_get:roborts_decision.MultiRobot.start_position)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::Point*>(
      &::roborts_decision::_Point_default_instance_);
}
inline ::roborts_decision::Point* MultiRobot::release_start_position() {
  // @@protoc_insertion_point(field_release:roborts_decision.MultiRobot.start_position)
  
  ::roborts_decision::Point* temp = start_position_;
  start_position_ = NULL;
  return temp;
}
inline ::roborts_decision::Point* MultiRobot::mutable_start_position() {
  
  if (start_position_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::Point>(GetArenaNoVirtual());
    start_position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.MultiRobot.start_position)
  return start_position_;
}
inline void MultiRobot::set_allocated_start_position(::roborts_decision::Point* start_position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete start_position_;
  }
  if (start_position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      start_position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, start_position, submessage_arena);
    }
    
  } else {
    
  }
  start_position_ = start_position;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.MultiRobot.start_position)
}

// -------------------------------------------------------------------

// BlueOrRedGroup

// .roborts_decision.MultiRobot master_bot = 1;
inline bool BlueOrRedGroup::has_master_bot() const {
  return this != internal_default_instance() && master_bot_ != NULL;
}
inline void BlueOrRedGroup::clear_master_bot() {
  if (GetArenaNoVirtual() == NULL && master_bot_ != NULL) {
    delete master_bot_;
  }
  master_bot_ = NULL;
}
inline const ::roborts_decision::MultiRobot& BlueOrRedGroup::_internal_master_bot() const {
  return *master_bot_;
}
inline const ::roborts_decision::MultiRobot& BlueOrRedGroup::master_bot() const {
  const ::roborts_decision::MultiRobot* p = master_bot_;
  // @@protoc_insertion_point(field_get:roborts_decision.BlueOrRedGroup.master_bot)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::MultiRobot*>(
      &::roborts_decision::_MultiRobot_default_instance_);
}
inline ::roborts_decision::MultiRobot* BlueOrRedGroup::release_master_bot() {
  // @@protoc_insertion_point(field_release:roborts_decision.BlueOrRedGroup.master_bot)
  
  ::roborts_decision::MultiRobot* temp = master_bot_;
  master_bot_ = NULL;
  return temp;
}
inline ::roborts_decision::MultiRobot* BlueOrRedGroup::mutable_master_bot() {
  
  if (master_bot_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::MultiRobot>(GetArenaNoVirtual());
    master_bot_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.BlueOrRedGroup.master_bot)
  return master_bot_;
}
inline void BlueOrRedGroup::set_allocated_master_bot(::roborts_decision::MultiRobot* master_bot) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete master_bot_;
  }
  if (master_bot) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      master_bot = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, master_bot, submessage_arena);
    }
    
  } else {
    
  }
  master_bot_ = master_bot;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.BlueOrRedGroup.master_bot)
}

// .roborts_decision.MultiRobot wing_bot = 2;
inline bool BlueOrRedGroup::has_wing_bot() const {
  return this != internal_default_instance() && wing_bot_ != NULL;
}
inline void BlueOrRedGroup::clear_wing_bot() {
  if (GetArenaNoVirtual() == NULL && wing_bot_ != NULL) {
    delete wing_bot_;
  }
  wing_bot_ = NULL;
}
inline const ::roborts_decision::MultiRobot& BlueOrRedGroup::_internal_wing_bot() const {
  return *wing_bot_;
}
inline const ::roborts_decision::MultiRobot& BlueOrRedGroup::wing_bot() const {
  const ::roborts_decision::MultiRobot* p = wing_bot_;
  // @@protoc_insertion_point(field_get:roborts_decision.BlueOrRedGroup.wing_bot)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::MultiRobot*>(
      &::roborts_decision::_MultiRobot_default_instance_);
}
inline ::roborts_decision::MultiRobot* BlueOrRedGroup::release_wing_bot() {
  // @@protoc_insertion_point(field_release:roborts_decision.BlueOrRedGroup.wing_bot)
  
  ::roborts_decision::MultiRobot* temp = wing_bot_;
  wing_bot_ = NULL;
  return temp;
}
inline ::roborts_decision::MultiRobot* BlueOrRedGroup::mutable_wing_bot() {
  
  if (wing_bot_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::MultiRobot>(GetArenaNoVirtual());
    wing_bot_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.BlueOrRedGroup.wing_bot)
  return wing_bot_;
}
inline void BlueOrRedGroup::set_allocated_wing_bot(::roborts_decision::MultiRobot* wing_bot) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete wing_bot_;
  }
  if (wing_bot) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      wing_bot = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, wing_bot, submessage_arena);
    }
    
  } else {
    
  }
  wing_bot_ = wing_bot;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.BlueOrRedGroup.wing_bot)
}

// .roborts_decision.Point reload_point = 3;
inline bool BlueOrRedGroup::has_reload_point() const {
  return this != internal_default_instance() && reload_point_ != NULL;
}
inline void BlueOrRedGroup::clear_reload_point() {
  if (GetArenaNoVirtual() == NULL && reload_point_ != NULL) {
    delete reload_point_;
  }
  reload_point_ = NULL;
}
inline const ::roborts_decision::Point& BlueOrRedGroup::_internal_reload_point() const {
  return *reload_point_;
}
inline const ::roborts_decision::Point& BlueOrRedGroup::reload_point() const {
  const ::roborts_decision::Point* p = reload_point_;
  // @@protoc_insertion_point(field_get:roborts_decision.BlueOrRedGroup.reload_point)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::Point*>(
      &::roborts_decision::_Point_default_instance_);
}
inline ::roborts_decision::Point* BlueOrRedGroup::release_reload_point() {
  // @@protoc_insertion_point(field_release:roborts_decision.BlueOrRedGroup.reload_point)
  
  ::roborts_decision::Point* temp = reload_point_;
  reload_point_ = NULL;
  return temp;
}
inline ::roborts_decision::Point* BlueOrRedGroup::mutable_reload_point() {
  
  if (reload_point_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::Point>(GetArenaNoVirtual());
    reload_point_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.BlueOrRedGroup.reload_point)
  return reload_point_;
}
inline void BlueOrRedGroup::set_allocated_reload_point(::roborts_decision::Point* reload_point) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reload_point_;
  }
  if (reload_point) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      reload_point = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, reload_point, submessage_arena);
    }
    
  } else {
    
  }
  reload_point_ = reload_point;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.BlueOrRedGroup.reload_point)
}

// .roborts_decision.Point shield_point = 4;
inline bool BlueOrRedGroup::has_shield_point() const {
  return this != internal_default_instance() && shield_point_ != NULL;
}
inline void BlueOrRedGroup::clear_shield_point() {
  if (GetArenaNoVirtual() == NULL && shield_point_ != NULL) {
    delete shield_point_;
  }
  shield_point_ = NULL;
}
inline const ::roborts_decision::Point& BlueOrRedGroup::_internal_shield_point() const {
  return *shield_point_;
}
inline const ::roborts_decision::Point& BlueOrRedGroup::shield_point() const {
  const ::roborts_decision::Point* p = shield_point_;
  // @@protoc_insertion_point(field_get:roborts_decision.BlueOrRedGroup.shield_point)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::Point*>(
      &::roborts_decision::_Point_default_instance_);
}
inline ::roborts_decision::Point* BlueOrRedGroup::release_shield_point() {
  // @@protoc_insertion_point(field_release:roborts_decision.BlueOrRedGroup.shield_point)
  
  ::roborts_decision::Point* temp = shield_point_;
  shield_point_ = NULL;
  return temp;
}
inline ::roborts_decision::Point* BlueOrRedGroup::mutable_shield_point() {
  
  if (shield_point_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::Point>(GetArenaNoVirtual());
    shield_point_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.BlueOrRedGroup.shield_point)
  return shield_point_;
}
inline void BlueOrRedGroup::set_allocated_shield_point(::roborts_decision::Point* shield_point) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete shield_point_;
  }
  if (shield_point) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      shield_point = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, shield_point, submessage_arena);
    }
    
  } else {
    
  }
  shield_point_ = shield_point;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.BlueOrRedGroup.shield_point)
}

// repeated .roborts_decision.Point patrol = 5;
inline int BlueOrRedGroup::patrol_size() const {
  return patrol_.size();
}
inline void BlueOrRedGroup::clear_patrol() {
  patrol_.Clear();
}
inline ::roborts_decision::Point* BlueOrRedGroup::mutable_patrol(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.BlueOrRedGroup.patrol)
  return patrol_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
BlueOrRedGroup::mutable_patrol() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.BlueOrRedGroup.patrol)
  return &patrol_;
}
inline const ::roborts_decision::Point& BlueOrRedGroup::patrol(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.BlueOrRedGroup.patrol)
  return patrol_.Get(index);
}
inline ::roborts_decision::Point* BlueOrRedGroup::add_patrol() {
  // @@protoc_insertion_point(field_add:roborts_decision.BlueOrRedGroup.patrol)
  return patrol_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
BlueOrRedGroup::patrol() const {
  // @@protoc_insertion_point(field_list:roborts_decision.BlueOrRedGroup.patrol)
  return patrol_;
}

// -------------------------------------------------------------------

// DecisionConfig

// string strategy = 1;
inline void DecisionConfig::clear_strategy() {
  strategy_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DecisionConfig::strategy() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.strategy)
  return strategy_.GetNoArena();
}
inline void DecisionConfig::set_strategy(const ::std::string& value) {
  
  strategy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.strategy)
}
#if LANG_CXX11
inline void DecisionConfig::set_strategy(::std::string&& value) {
  
  strategy_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:roborts_decision.DecisionConfig.strategy)
}
#endif
inline void DecisionConfig::set_strategy(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  strategy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_decision.DecisionConfig.strategy)
}
inline void DecisionConfig::set_strategy(const char* value, size_t size) {
  
  strategy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_decision.DecisionConfig.strategy)
}
inline ::std::string* DecisionConfig::mutable_strategy() {
  
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.strategy)
  return strategy_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DecisionConfig::release_strategy() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.strategy)
  
  return strategy_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DecisionConfig::set_allocated_strategy(::std::string* strategy) {
  if (strategy != NULL) {
    
  } else {
    
  }
  strategy_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strategy);
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.strategy)
}

// bool use_camera = 2;
inline void DecisionConfig::clear_use_camera() {
  use_camera_ = false;
}
inline bool DecisionConfig::use_camera() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.use_camera)
  return use_camera_;
}
inline void DecisionConfig::set_use_camera(bool value) {
  
  use_camera_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.use_camera)
}

// bool master = 3;
inline void DecisionConfig::clear_master() {
  master_ = false;
}
inline bool DecisionConfig::master() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.master)
  return master_;
}
inline void DecisionConfig::set_master(bool value) {
  
  master_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.master)
}

// bool isblue = 4;
inline void DecisionConfig::clear_isblue() {
  isblue_ = false;
}
inline bool DecisionConfig::isblue() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.isblue)
  return isblue_;
}
inline void DecisionConfig::set_isblue(bool value) {
  
  isblue_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.isblue)
}

// bool usewifi = 5;
inline void DecisionConfig::clear_usewifi() {
  usewifi_ = false;
}
inline bool DecisionConfig::usewifi() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.usewifi)
  return usewifi_;
}
inline void DecisionConfig::set_usewifi(bool value) {
  
  usewifi_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.usewifi)
}

// string master_ip = 6;
inline void DecisionConfig::clear_master_ip() {
  master_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DecisionConfig::master_ip() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.master_ip)
  return master_ip_.GetNoArena();
}
inline void DecisionConfig::set_master_ip(const ::std::string& value) {
  
  master_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.master_ip)
}
#if LANG_CXX11
inline void DecisionConfig::set_master_ip(::std::string&& value) {
  
  master_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:roborts_decision.DecisionConfig.master_ip)
}
#endif
inline void DecisionConfig::set_master_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  master_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_decision.DecisionConfig.master_ip)
}
inline void DecisionConfig::set_master_ip(const char* value, size_t size) {
  
  master_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_decision.DecisionConfig.master_ip)
}
inline ::std::string* DecisionConfig::mutable_master_ip() {
  
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.master_ip)
  return master_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DecisionConfig::release_master_ip() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.master_ip)
  
  return master_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DecisionConfig::set_allocated_master_ip(::std::string* master_ip) {
  if (master_ip != NULL) {
    
  } else {
    
  }
  master_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), master_ip);
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.master_ip)
}

// string guard_ip = 7;
inline void DecisionConfig::clear_guard_ip() {
  guard_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DecisionConfig::guard_ip() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.guard_ip)
  return guard_ip_.GetNoArena();
}
inline void DecisionConfig::set_guard_ip(const ::std::string& value) {
  
  guard_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.guard_ip)
}
#if LANG_CXX11
inline void DecisionConfig::set_guard_ip(::std::string&& value) {
  
  guard_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:roborts_decision.DecisionConfig.guard_ip)
}
#endif
inline void DecisionConfig::set_guard_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  guard_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_decision.DecisionConfig.guard_ip)
}
inline void DecisionConfig::set_guard_ip(const char* value, size_t size) {
  
  guard_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_decision.DecisionConfig.guard_ip)
}
inline ::std::string* DecisionConfig::mutable_guard_ip() {
  
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.guard_ip)
  return guard_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DecisionConfig::release_guard_ip() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.guard_ip)
  
  return guard_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DecisionConfig::set_allocated_guard_ip(::std::string* guard_ip) {
  if (guard_ip != NULL) {
    
  } else {
    
  }
  guard_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), guard_ip);
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.guard_ip)
}

// int32 remain_bullet = 8;
inline void DecisionConfig::clear_remain_bullet() {
  remain_bullet_ = 0;
}
inline ::google::protobuf::int32 DecisionConfig::remain_bullet() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.remain_bullet)
  return remain_bullet_;
}
inline void DecisionConfig::set_remain_bullet(::google::protobuf::int32 value) {
  
  remain_bullet_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.remain_bullet)
}

// .roborts_decision.EscapeConstraint escape = 9;
inline bool DecisionConfig::has_escape() const {
  return this != internal_default_instance() && escape_ != NULL;
}
inline void DecisionConfig::clear_escape() {
  if (GetArenaNoVirtual() == NULL && escape_ != NULL) {
    delete escape_;
  }
  escape_ = NULL;
}
inline const ::roborts_decision::EscapeConstraint& DecisionConfig::_internal_escape() const {
  return *escape_;
}
inline const ::roborts_decision::EscapeConstraint& DecisionConfig::escape() const {
  const ::roborts_decision::EscapeConstraint* p = escape_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.escape)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::EscapeConstraint*>(
      &::roborts_decision::_EscapeConstraint_default_instance_);
}
inline ::roborts_decision::EscapeConstraint* DecisionConfig::release_escape() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.escape)
  
  ::roborts_decision::EscapeConstraint* temp = escape_;
  escape_ = NULL;
  return temp;
}
inline ::roborts_decision::EscapeConstraint* DecisionConfig::mutable_escape() {
  
  if (escape_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::EscapeConstraint>(GetArenaNoVirtual());
    escape_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.escape)
  return escape_;
}
inline void DecisionConfig::set_allocated_escape(::roborts_decision::EscapeConstraint* escape) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete escape_;
  }
  if (escape) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      escape = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, escape, submessage_arena);
    }
    
  } else {
    
  }
  escape_ = escape;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.escape)
}

// .roborts_decision.BlueOrRedGroup blue = 10;
inline bool DecisionConfig::has_blue() const {
  return this != internal_default_instance() && blue_ != NULL;
}
inline void DecisionConfig::clear_blue() {
  if (GetArenaNoVirtual() == NULL && blue_ != NULL) {
    delete blue_;
  }
  blue_ = NULL;
}
inline const ::roborts_decision::BlueOrRedGroup& DecisionConfig::_internal_blue() const {
  return *blue_;
}
inline const ::roborts_decision::BlueOrRedGroup& DecisionConfig::blue() const {
  const ::roborts_decision::BlueOrRedGroup* p = blue_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.blue)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::BlueOrRedGroup*>(
      &::roborts_decision::_BlueOrRedGroup_default_instance_);
}
inline ::roborts_decision::BlueOrRedGroup* DecisionConfig::release_blue() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.blue)
  
  ::roborts_decision::BlueOrRedGroup* temp = blue_;
  blue_ = NULL;
  return temp;
}
inline ::roborts_decision::BlueOrRedGroup* DecisionConfig::mutable_blue() {
  
  if (blue_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::BlueOrRedGroup>(GetArenaNoVirtual());
    blue_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.blue)
  return blue_;
}
inline void DecisionConfig::set_allocated_blue(::roborts_decision::BlueOrRedGroup* blue) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete blue_;
  }
  if (blue) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      blue = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, blue, submessage_arena);
    }
    
  } else {
    
  }
  blue_ = blue;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.blue)
}

// .roborts_decision.BlueOrRedGroup red = 11;
inline bool DecisionConfig::has_red() const {
  return this != internal_default_instance() && red_ != NULL;
}
inline void DecisionConfig::clear_red() {
  if (GetArenaNoVirtual() == NULL && red_ != NULL) {
    delete red_;
  }
  red_ = NULL;
}
inline const ::roborts_decision::BlueOrRedGroup& DecisionConfig::_internal_red() const {
  return *red_;
}
inline const ::roborts_decision::BlueOrRedGroup& DecisionConfig::red() const {
  const ::roborts_decision::BlueOrRedGroup* p = red_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.red)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::BlueOrRedGroup*>(
      &::roborts_decision::_BlueOrRedGroup_default_instance_);
}
inline ::roborts_decision::BlueOrRedGroup* DecisionConfig::release_red() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.red)
  
  ::roborts_decision::BlueOrRedGroup* temp = red_;
  red_ = NULL;
  return temp;
}
inline ::roborts_decision::BlueOrRedGroup* DecisionConfig::mutable_red() {
  
  if (red_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::BlueOrRedGroup>(GetArenaNoVirtual());
    red_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.red)
  return red_;
}
inline void DecisionConfig::set_allocated_red(::roborts_decision::BlueOrRedGroup* red) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete red_;
  }
  if (red) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      red = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, red, submessage_arena);
    }
    
  } else {
    
  }
  red_ = red;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.red)
}

// .roborts_decision.SearchConstraint search_limit = 12;
inline bool DecisionConfig::has_search_limit() const {
  return this != internal_default_instance() && search_limit_ != NULL;
}
inline void DecisionConfig::clear_search_limit() {
  if (GetArenaNoVirtual() == NULL && search_limit_ != NULL) {
    delete search_limit_;
  }
  search_limit_ = NULL;
}
inline const ::roborts_decision::SearchConstraint& DecisionConfig::_internal_search_limit() const {
  return *search_limit_;
}
inline const ::roborts_decision::SearchConstraint& DecisionConfig::search_limit() const {
  const ::roborts_decision::SearchConstraint* p = search_limit_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_limit)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::SearchConstraint*>(
      &::roborts_decision::_SearchConstraint_default_instance_);
}
inline ::roborts_decision::SearchConstraint* DecisionConfig::release_search_limit() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.search_limit)
  
  ::roborts_decision::SearchConstraint* temp = search_limit_;
  search_limit_ = NULL;
  return temp;
}
inline ::roborts_decision::SearchConstraint* DecisionConfig::mutable_search_limit() {
  
  if (search_limit_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::SearchConstraint>(GetArenaNoVirtual());
    search_limit_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_limit)
  return search_limit_;
}
inline void DecisionConfig::set_allocated_search_limit(::roborts_decision::SearchConstraint* search_limit) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete search_limit_;
  }
  if (search_limit) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      search_limit = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, search_limit, submessage_arena);
    }
    
  } else {
    
  }
  search_limit_ = search_limit;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.search_limit)
}

// .roborts_decision.WhirlVel whirl_vel = 13;
inline bool DecisionConfig::has_whirl_vel() const {
  return this != internal_default_instance() && whirl_vel_ != NULL;
}
inline void DecisionConfig::clear_whirl_vel() {
  if (GetArenaNoVirtual() == NULL && whirl_vel_ != NULL) {
    delete whirl_vel_;
  }
  whirl_vel_ = NULL;
}
inline const ::roborts_decision::WhirlVel& DecisionConfig::_internal_whirl_vel() const {
  return *whirl_vel_;
}
inline const ::roborts_decision::WhirlVel& DecisionConfig::whirl_vel() const {
  const ::roborts_decision::WhirlVel* p = whirl_vel_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.whirl_vel)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::WhirlVel*>(
      &::roborts_decision::_WhirlVel_default_instance_);
}
inline ::roborts_decision::WhirlVel* DecisionConfig::release_whirl_vel() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.whirl_vel)
  
  ::roborts_decision::WhirlVel* temp = whirl_vel_;
  whirl_vel_ = NULL;
  return temp;
}
inline ::roborts_decision::WhirlVel* DecisionConfig::mutable_whirl_vel() {
  
  if (whirl_vel_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::WhirlVel>(GetArenaNoVirtual());
    whirl_vel_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.whirl_vel)
  return whirl_vel_;
}
inline void DecisionConfig::set_allocated_whirl_vel(::roborts_decision::WhirlVel* whirl_vel) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete whirl_vel_;
  }
  if (whirl_vel) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      whirl_vel = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, whirl_vel, submessage_arena);
    }
    
  } else {
    
  }
  whirl_vel_ = whirl_vel;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.whirl_vel)
}

// repeated .roborts_decision.Point search_region_1 = 14;
inline int DecisionConfig::search_region_1_size() const {
  return search_region_1_.size();
}
inline void DecisionConfig::clear_search_region_1() {
  search_region_1_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_1(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_1() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_1)
  return &search_region_1_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_1(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_1() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_1() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_;
}

// repeated .roborts_decision.Point search_region_2 = 15;
inline int DecisionConfig::search_region_2_size() const {
  return search_region_2_.size();
}
inline void DecisionConfig::clear_search_region_2() {
  search_region_2_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_2(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_2() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_2)
  return &search_region_2_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_2(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_2() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_2() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_;
}

// repeated .roborts_decision.Point search_region_3 = 16;
inline int DecisionConfig::search_region_3_size() const {
  return search_region_3_.size();
}
inline void DecisionConfig::clear_search_region_3() {
  search_region_3_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_3(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_3() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_3)
  return &search_region_3_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_3(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_3() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_3() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_;
}

// repeated .roborts_decision.Point search_region_4 = 17;
inline int DecisionConfig::search_region_4_size() const {
  return search_region_4_.size();
}
inline void DecisionConfig::clear_search_region_4() {
  search_region_4_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_4(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_4() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_4)
  return &search_region_4_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_4(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_4() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_4() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_;
}

// bool can_shoot = 18;
inline void DecisionConfig::clear_can_shoot() {
  can_shoot_ = false;
}
inline bool DecisionConfig::can_shoot() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.can_shoot)
  return can_shoot_;
}
inline void DecisionConfig::set_can_shoot(bool value) {
  
  can_shoot_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.can_shoot)
}

// int32 shoot_hz = 19;
inline void DecisionConfig::clear_shoot_hz() {
  shoot_hz_ = 0;
}
inline ::google::protobuf::int32 DecisionConfig::shoot_hz() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.shoot_hz)
  return shoot_hz_;
}
inline void DecisionConfig::set_shoot_hz(::google::protobuf::int32 value) {
  
  shoot_hz_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.shoot_hz)
}

// bool use_refree = 20;
inline void DecisionConfig::clear_use_refree() {
  use_refree_ = false;
}
inline bool DecisionConfig::use_refree() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.use_refree)
  return use_refree_;
}
inline void DecisionConfig::set_use_refree(bool value) {
  
  use_refree_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.use_refree)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_decision

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_decision_2eproto
